### ISSUE TITLE
Add CIM version

### ISSUE THREAD

**Issue by bartkl** [Netbeheer-Nederland/linkml-asciidoc-generator#12]
The CIM version the model is based on should be mentioned somewhere.

This also means the version should be mentioned in the LinkML schema I'd say.

**Comment by bartkl** [comment]
```yaml
id: https://cim.ucaiug.io/ns#TC57CIM
name: TC57CIM
title: TC57CIM
contributors:
- github:bartkl
created_by: https://github.com/bartkl/cim-to-linkml
generation_date: 2026-05-11 20:07:27.468378
license: https://www.apache.org/licenses/LICENSE-2.0.txt
metamodel_version: 1.7.0
```

This should be improved:

```yaml
id: https://cim.ucaiug.io/ns#TC57CIM
name: TC57CIM
title: TC57CIM
contributors:
- github:bartkl
created_by: https://github.com/netbeheer-nederland/cim-to-linkml
generation_date: 2026-05-11 20:07:27.468378
license: https://www.apache.org/licenses/LICENSE-2.0.txt
metamodel_version: 1.7.0
source: iec61970cim17v40_iec61968cim13v13b_iec62325cim03v17b_CIM100.1.1.1.qea
```
