### ISSUE TITLE
Empty enum values cause parsing error

### ISSUE THREAD

**Issue by bartkl** [Netbeheer-Nederland/linkml-asciidoc-generator#28]
When enum values have no body like so:

```yaml
enums:
  AccumulationKind:
    permissible_values:
      boundedQuantity:
      bulkQuantity:
```

This causes a parsing error (caution: this error message is from a different example):

```shell
enums.SystemOperatorNameCode.permissible_values.Rendo
  Input should be a valid dictionary or instance of PermissibleValue [type=model_type, input_value=None, input_type=NoneType]
```

What _does_ work is when the keys have bodies:

```yaml
enums:
  AccumulationKind:
    enum_uri: cim:AccumulationKind
    permissible_values:
      boundedQuantity:
        description: Something...
      bulkQuantity:
        meaning: cim:AccumulationKind.bulkQuantity
```

Yet another reason to use the actual `SchemaView`.
